apiVersion: v1
kind: Pod
metadata:
  name: helloworld.oracleau.cloud
  labels:
    app: helloworld.oracleau.cloud
spec:
  containers:
  - name: helloworldk8sdemo
    image: cciturria/helloworldk8sdemo
    ports:
    - name: nodejs-port
      containerPort: 3000
